#!/bin/bash

#--------------------------------------------
# 功能：为使用了CocoaPods的工程打ipa包
# 使用说明：	cocoapods-build <cococapods project path> [<build configuration>]
#--------------------------------------------


#参数判断
if [ $# != 3 ] && [ $# != 2 ] && [ $# != 1 ];then
	echo "Number of params error!"
	echo "1.path of project(necessary) 2.packagetype(adhoc, inhouse, appstore) 3.(Release, Debug)"
	exit	
elif [ ! -d $1 ];then
	echo "Params Error!! The first param must be a directory."
	exit	
fi


#获取shell文件所在的绝对路径
current_path=$(pwd)
tmp_path=$(dirname $0)
cd $tmp_path
shell_path=$(pwd)
cd $current_path


#工程绝对路径
echo $1
cd $1

# #build bundle
# cd OpenAccount
# rm -rf build
# xcodebuild -scheme OpenAccountRes
# cd ../

# cd ZTBStock
# rm -rf build
# xcodebuild -scheme ZTBStockRes
# cd ../

# cd TZYJ_IPhone/Resources
# cp TZYJ_IPhone_${packagetype}.entitlements TZYJ_IPhone.entitlements
# cd ../../


#更新Pod
# pod install --verbose

project_path=$(pwd)
#获取工程默认scheme的名字（默认与工程文件名字相同）
scheme_name=$(echo $(basename ./*.xcodeproj) | awk -F. '{print $1}')


build_cmd=${shell_path}'/ipa-build '${project_path}' -w -s '${scheme_name}

if [ $# = 2 ];then
	build_cmd=${build_cmd}' -n -m '$2
fi

if [ $# = 3 ];then
	build_cmd=${build_cmd}' -n -m '$2' -c '$3
fi


#编译工程
${build_cmd} 


