#!/bin/bash

#--------------------------------------------
# 功能：编译xcode项目并打ipa包
# 使用说明：
#		编译project
#			ipa-build <project directory> [-c <project configuration>] [-o <ipa output directory>] [-t <target name>] [-n] [-p <platform identifier>]
#		编译workspace
#			ipa-build  <workspace directory> -w -s <schemeName> [-c <project configuration>] [-n]
#
# 参数说明： -c NAME				工程的configuration,默认为Release。
#			-o PATH				生成的ipa文件输出的文件夹（必须为已存在的文件路径）默认为工程根路径下的”build/ipa-build“文件夹中
#			-t NAME				需要编译的target的名称
#			-w					编译workspace
#			-s NAME				对应workspace下需要编译的scheme
#			-n					编译前是否先clean工程
#			-p					平台标识符

#			-m					待读取的mobileprovision的前缀adhoc, inhouse, appstore
#--------------------------------------------

export PATH=$PATH:/usr/libexec

if [ $# -lt 1 ];then
	echo "Error! Should enter the root directory of xcode project after the ipa-build command."
	exit 2
fi

if [ ! -d $1 ];then
	echo "Error! The first param must be a directory."
	exit 2
fi

#工程绝对路径
cd $1
project_path=$(pwd)

#编译的configuration，默认为Release
build_config=Release

#gcc_define="JENKINS=1"
gcc_define="$JENKINS_PAR_GCC"


mobileprovision=notset


#param_pattern中第一个冒号表示忽略错误，字符后面的冒号表示该选项必须有自己的参数
param_pattern=":p:nc:m:o:t:ws:"
OPTIND=2
while getopts $param_pattern optname
  do
    case "$optname" in

	  "n")
		should_clean=y
        ;;
      "p")
		tmp_optind=$OPTIND
		tmp_optname=$optname
		tmp_optarg=$OPTARG

		OPTIND=$OPTIND-1
		if getopts $param_pattern optname ;then
			echo  "Error argument value for option $tmp_optname"
			exit 2
		fi
		OPTIND=$tmp_optind

		platform_id=$tmp_optarg

        ;;
      "c")
		tmp_optind=$OPTIND
		tmp_optname=$optname
		tmp_optarg=$OPTARG
		OPTIND=$OPTIND-1
		if getopts $param_pattern optname ;then
			echo  "Error argument value for option $tmp_optname"
			exit 2
		fi
		OPTIND=$tmp_optind

		build_config=$tmp_optarg

        ;;
      "m")
		tmp_optind=$OPTIND
		tmp_optname=$optname
		tmp_optarg=$OPTARG
		OPTIND=$OPTIND-1
		if getopts $param_pattern optname ;then
			echo  "Error argument value for option $tmp_optname"
			exit 2
		fi
		OPTIND=$tmp_optind

		mobileprovision=$tmp_optarg

        ;;
      "o")
		tmp_optind=$OPTIND
		tmp_optname=$optname
		tmp_optarg=$OPTARG

		OPTIND=$OPTIND-1
		if getopts $param_pattern optname ;then
			echo  "Error argument value for option $tmp_optname"
			exit 2
		fi
		OPTIND=$tmp_optind


		cd $tmp_optarg
		output_path=$(pwd)
		cd ${project_path}

		if [ ! -d $output_path ];then
			echo "Error!The value of option o must be an exist directory."
			exit 2
		fi

        ;;
	  "w")
		workspace_name='*.xcworkspace'
		ls $project_path/$workspace_name &>/dev/null
		rtnValue=$?
		if [ $rtnValue = 0 ];then
			build_workspace=$(echo $(basename $project_path/$workspace_name))
		else
			echo  "Error!Current path is not a xcode workspace.Please check, or do not use -w option."
			exit 2
		fi

        ;;
	  "s")
		tmp_optind=$OPTIND
		tmp_optname=$optname
		tmp_optarg=$OPTARG

		OPTIND=$OPTIND-1
		if getopts $param_pattern optname ;then
			echo  "Error argument value for option $tmp_optname"
			exit 2
		fi
		OPTIND=$tmp_optind

		build_scheme=$tmp_optarg

        ;;
	  "t")
		tmp_optind=$OPTIND
		tmp_optname=$optname
		tmp_optarg=$OPTARG

		OPTIND=$OPTIND-1
		if getopts $param_pattern optname ;then
			echo  "Error argument value for option $tmp_optname"
			exit 2
		fi
		OPTIND=$tmp_optind

		build_target=$tmp_optarg

        ;;


      "?")
        echo "Error! Unknown option $OPTARG"
		exit 2
        ;;
      ":")
        echo "Error! No argument value for option $OPTARG"
		exit 2
        ;;
      *)
      # Should not occur
        echo "Error! Unknown error while processing options"
		exit 2
        ;;
    esac
  done


#build文件夹路径
build_path=${project_path}/build
rm -rf build

#生成的app文件目录
appdirname=Release-iphoneos
if [ $build_config = Debug ];then
	appdirname=Debug-iphoneos
fi
if [ $build_config = Distribute ];then
	appdirname=Distribute-iphoneos
fi
#编译后文件路径(仅当编译workspace时才会用到)
compiled_path=${build_path}/${appdirname}
archivePath=${build_path}/${build_scheme}.xcarchive


#是否clean
if [ "$should_clean" = "y" ];then
	xcodebuild clean -configuration ${build_config}
fi


#组合编译命令
build_cmd='xcodebuild'

if [ "$build_workspace" != "" ];then
	#编译workspace
	if [ "$build_scheme" = "" ];then
		echo "Error! Must provide a scheme by -s option together when using -w option to compile a workspace."
		exit 2
	fi

	build_cmd=${build_cmd}' -workspace '${build_workspace}' -scheme '${build_scheme}' -configuration '${build_config}' CONFIGURATION_BUILD_DIR='${compiled_path}' ONLY_ACTIVE_ARCH=NO GCC_PREPROCESSOR_DEFINITIONS="'${gcc_define}'"'

else
	#编译project
	build_cmd=${build_cmd}' -configuration '${build_config}

	if [ "$build_target" != "" ];then
		build_cmd=${build_cmd}' -target '${build_target}
	fi

fi


#设置build号 为Jenkins环境变量 相应值 -- 编译之前修改版本号
info_path=${project_path}/${build_scheme}/${build_scheme}-Info.plist

#xcrun agvtool new-version -all ${BUILD_NUMBER}
if [ $BUILD_NUMBER != "" ];then
	PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ${info_path}
	echo "BUILD_NUMBER is $BUILD_NUMBER"
else
	echo "BUILD_NUMBER is null"
fi

if [ $mobileprovision != notset ];then

	netconfig_path=${project_path}/${build_scheme}/Configs/netConfig.plist
	PlistBuddy -c "Set :CurrentEnv ${environment}" ${netconfig_path}

	mobileprovision_file=${project_path}/xcode_shell_new/${packagetype}.mobileprovision
	exportOptionsPlist=${project_path}/xcode_shell_new/${packagetype}.plist
	open "${mobileprovision_file}"
	sleep 5

	UUID=`PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i $mobileprovision_file)`
	echo "mobileprovision_file UUID is: ${UUID}"

	Name=`PlistBuddy -c "Print Name" /dev/stdin <<< $(/usr/bin/security cms -D -i $mobileprovision_file)`
	echo "mobileprovision_file Name is: ${Name}"

	TeamName=`PlistBuddy -c "Print TeamName" /dev/stdin <<< $(/usr/bin/security cms -D -i $mobileprovision_file)`
	echo "mobileprovision_file TeamName is: ${TeamName}"

	team_identifier=`PlistBuddy -c "Print Entitlements:com.apple.developer.team-identifier" /dev/stdin <<< $(/usr/bin/security cms -D -i $mobileprovision_file)`
	echo "mobileprovision_file team_identifier is: ${team_identifier}"

	identifier=`PlistBuddy -c "Print Entitlements:application-identifier" /dev/stdin <<< $(/usr/bin/security cms -D -i $mobileprovision_file)`
	identifier=${identifier#*.}
	echo "mobileprovision_file identifier is: ${identifier}"


	build_identifier=${identifier}
	build_identity=${TeamName}
	build_profile=${UUID}

	build_specifier=${team_identifier}/${Name}

	PlistBuddy -c "Set :CFBundleIdentifier ${build_identifier}" ${info_path}

	bundleName=${identifier##*.}
	#PlistBuddy -c "Set :CFBundleName ${bundleName}" ${info_path}

	build_cmd=${build_cmd}'  -archivePath '${archivePath}' archive '
fi

echo "build_cmd is :\n $build_cmd"


# ================================================= 编译工程 ======================================== #
cd $project_path
eval $build_cmd || exit



# =============================== 定义构建输出路径，export ipa, xcarchive ============================= #
#进入build路径
cd $build_path

#创建ipa-build文件夹
# if [ -d ./ipa-build ];then
# 	rm -rf ipa-build
# fi
# mkdir ipa-build



#app文件名称
# appname=$(basename ./${appdirname}/*.app)
#通过app文件名获得工程target名字
target_name=${build_scheme}


#app文件中Info.plist文件路径
app_infoplist_path=${info_path}
#取版本号
bundleShortVersion=$(PlistBuddy -c "print CFBundleShortVersionString" ${app_infoplist_path})
#取build值
bundleVersion=$BUILD_NUMBER
#取displayName
displayName=$(PlistBuddy -c "print CFBundleDisplayName" ${app_infoplist_path})

#取bundleName
# bundleName=$(PlistBuddy -c "print CFBundleName" ${app_infoplist_path})
bundleName=${build_scheme}

bundleIdentifier=$(PlistBuddy -c "print CFBundleIdentifier" ${app_infoplist_path})
#IPA名称
ipa_name="${bundleName}_${bundleShortVersion}_M${bundleVersion}"
echo $ipa_name

#xcrun打包
#xcrun -sdk iphoneos PackageApplication -v ./${appdirname}/*.app -o ${build_path}/ipa-build/${ipa_name}.ipa || exit
xcodebuild -exportArchive -archivePath ${archivePath} -exportOptionsPlist ${exportOptionsPlist}  -exportPath ${build_path}/ipa-build/  || exit

mv ${build_path}/ipa-build/*.ipa ${build_path}/ipa-build/${ipa_name}_${TagOrBranch#*/}_${environment}_${packagetype}.ipa

if [ "$output_path" != "" ];then
	cp ${build_path}/ipa-build/${ipa_name}.ipa $output_path/${ipa_name}.ipa
	echo "Copy ipa file successfully to the path $output_path/${ipa_name}.ipa"
fi


if [ "$BUILD_NUMBER" = "" ];then
	echo "local build done!"
	exit
fi

if [ $mobileprovision = appstore ];then
	exit
fi




# =============================== 定义发布路径，拷贝ipa到相应路径下 ============================= #
#获取shell文件所在的绝对路径
current_path=$(pwd)
tmp_path=$(dirname $0)
cd $tmp_path
shell_path=$(pwd)
cd $current_path


#发布应用的url地址
# pulish_ip="jenkins.shhxzq.com"
# pulish_url="https://${pulish_ip}"
pulish_ip="localhost:8080"
pulish_url="http://${pulish_ip}"

# www_dir="/Users/admin/Sites/localhost"
www_dir="/Users/Dyy/.jenkins/userContent"
relative_dir_ipa="ios/${bundleName}/${bundleShortVersion}/packages"
relative_dir_index="ios/${bundleName}/${bundleShortVersion}/M${bundleVersion}"
relative_dir_latest="ios/${bundleName}/latest"
www_dir_ipa="${www_dir}/${relative_dir_ipa}"
www_dir_index="${www_dir}/${relative_dir_index}"
www_dir_latest="${www_dir}/${relative_dir_latest}"

mkdir -p ${www_dir_ipa}
mkdir -p ${www_dir_index}
mkdir -p ${www_dir_latest}

#调用upload脚本来将文件上传到服务器
# ${shell_path}/scp_upload ${pulish_ip} ${pulish_port} ${pulish_user} ${pulish_pwd} ${build_path}/ipa-build/${ipa_name}.ipa /var/www/ota/ios/${bundleName}/${bundleShortVersion}/packages
cp ${build_path}/ipa-build/*.ipa ${www_dir_ipa}/${ipa_name}.ipa

#显示名称
ios_title="${displayName}"
ios_version="${bundleShortVersion}"
bundleIdentifier="${bundleIdentifier}"
ios_build="${bundleVersion}"
ios_install_url="${pulish_url}/${relative_dir_index}/${target_name}.plist"
ipa_url="${pulish_url}/${relative_dir_ipa}/${ipa_name}.ipa"
# ios_install_url="${pulish_url}/ios/${bundleName}/${bundleShortVersion}/M${bundleVersion}/${target_name}.plist"
# ipa_url="${pulish_url}/ios/${bundleName}/${bundleShortVersion}/packages/${ipa_name}.ipa"
#ipa_url="http://192.168.21.165:8080/job/$JOB_NAME/$BUILD_NUMBER/artifact/build/ipa-build/${ipa_name}.ipa"

rm index.html
rm ${target_name}.plist




# ========================================== 生成html文件 ======================================== #
cat << EOF > index.html
<!DOCTYPE html>
<!--[if IE 7]> <html lang="en" class="ie7"> <![endif]-->
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<head>
    <title>${title}</title>
        <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link rel="shortcut icon" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/img/favicon.ico" />

    <!-- CSS Global Compulsory-->
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/plugins/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/css/style.css" />

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/plugins/line-icons/line-icons.css">
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/plugins/flexslider/flexslider.css">
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/plugins/bxslider/jquery.bxslider.css">
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/plugins/horizontal-parallax/css/horizontal-parallax.css">

    <!-- CSS Theme -->
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/css/themes/default.css" id="style_color">

    <!-- CSS Customization -->
    <link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/css/custom.css">
</head>

<body>

<!-- wechat share icon -->
<div style="display:none;">
    <img src="./Icon.png" />
</div>

<!--=== Breadcrumbs ===-->
<div class="row-fluid breadcrumbs margin-bottom-20">
    <div class="container">
        <h1 class="pull-left">${ios_title}</h1>
        <ul class="pull-right breadcrumb">
            <li>版本：${ios_version} (build ${ios_build})</li>
        </ul>
    </div><!--/container-->
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->

<!--=== Content Part ===-->
<div class="container content">

    <div id="" class="view row" style="margin-top:30px;">
            <div class="span12 margin-bottom-20" style="text-align:center;">
                <div class="spinner">
                    <a href="${pulish_url}/ca.crt ">安装crt服务器证书(只需首次)</a>
                </div>
            </div>

            <hr class="devider devider-dotted">
            <div class="span12 margin-bottom-20" style="text-align:center;">
                <div class="spinner">
                    <a href="itms-services://?action=download-manifest&url=${ios_install_url}">点击安装App或扫码安装</a>
                </div>
            </div>

            <hr class="devider devider-dotted" />
            <div class="span12 margin-bottom-20" style="text-align:center;">
                 <img src="http://wccios.alpha.wochacha.com:7788/do/qrcode/${pulish_url}/${relative_dir_index}/">
            </div>
            <hr class="devider devider-dotted" />

    </div><!--/container-->
<!--=== End Content Part ===-->

<!--=== Copyright ===-->
<link rel="stylesheet" href="https://o1wjx1evz.qnssl.com/static-20160507/assets/plugins/sky-forms/version-2.0.1/css/custom-sky-forms.css">
<style>
.state-error em{
    margin-top: 6px;
    padding: 0 1px;
    font-style: normal;
    font-size: 11px;
    line-height: 15px;
    color: #ee9393;
}
#formReport section{ font-size:14px !important}
.btn-u.btn-u-default {
    background-color: #ebebeb;
    border-color: #adadad;
    color: #333;
}
.sky-form a.btn-u {
    color: #333;
}
.sky-form a.btn-u:hover {color:#fff}
</style>
<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-lg-8  col-xs-12 col-md-6 col-sm-6 text-left">
                        本页面由 <a href="/">上海华信证券</a> 提供<a class='footer_faq' href="httt://shhxzq.com"/a>
            </div>
        </div><!--/row-fluid-->
    </div><!--/container-->
</div>
<div class="modal fade addmodel" id="reportApp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>


</body>
</html>

EOF




# ============================================= 生成plist文件 ==================================#
cat << EOF > ${target_name}.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>items</key>
	<array>
		<dict>
			<key>assets</key>
			<array>
				<dict>
					<key>kind</key>
					<string>software-package</string>
					<key>url</key>
					<string>${ipa_url}</string>
				</dict>
				<dict>
					<key>kind</key>
					<string>display-image</string>
					<key>url</key>
					<string>https://app.shhxzq.com/static/android/display-image.png</string>
				</dict>
				<dict>
					<key>kind</key>
					<string>full-size-image</string>
					<key>url</key>
					<string>https://app.shhxzq.com/static/android/full-size-image.png</string>
				</dict>
			</array>
			<key>metadata</key>
			<dict>
				<key>bundle-identifier</key>
				<string>${bundleIdentifier}</string>
				<key>bundle-version</key>
				<string>${ios_version}</string>
				<key>kind</key>
				<string>software</string>
				<key>title</key>
				<string>${ios_title}</string>
			</dict>
		</dict>
	</array>
</dict>
</plist>

EOF



# =============================== 拷贝index.html文件、.plist文件至发布路径下 ============================= #

# ${shell_path}/scp_upload ${pulish_ip} ${pulish_port} ${pulish_user} ${pulish_pwd} ${build_path}/index.html /var/www/ota/ios/${bundleName}/${bundleShortVersion}/M${bundleVersion}
# ${shell_path}/scp_upload ${pulish_ip} ${pulish_port} ${pulish_user} ${pulish_pwd} ${build_path}/${target_name}.plist /var/www/ota/ios/${bundleName}/${bundleShortVersion}/M${bundleVersion}

# echo "install this version: ${pulish_url}/ios/${bundleName}/${bundleShortVersion}/M${bundleVersion}/"

# ${shell_path}/scp_upload ${pulish_ip} ${pulish_port} ${pulish_user} ${pulish_pwd} ${build_path}/index.html /var/www/ota/ios/${bundleName}/latest/
# echo "latest version: ${pulish_url}/ios/${bundleName}/latest/"


cp ${build_path}/index.html ${www_dir_index}
cp ${build_path}/${target_name}.plist ${www_dir_index}
echo "install this version: ${pulish_url}/${relative_dir_index}"

cp ${build_path}/index.html ${www_dir_latest}
echo "latest version: ${pulish_url}/${relative_dir_latest}/"
